apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-platform.fullname" . }}-open-webui-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  WEBUI_AUTH_SECRET_KEY: {{ .Values.openWebUI.secret.authSecretKey | quote }}