apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform.fullname" . }}-open-webui
  namespace: {{ .Values.namespace }}

  labels:
    app: open-webui

spec:
  type: {{ .Values.openWebUI.service.type }}

  selector:
    app: open-webui

  ports:
    - name: http
      port: {{ .Values.openWebUI.service.port }}
      targetPort: {{ .Values.openWebUI.service.targetPort }}
      nodePort: {{ .Values.openWebUI.service.nodePort }}
      protocol: TCP