apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform.fullname" . }}-ollama
  namespace: {{ .Values.namespace }}
  labels:
    app: ollama

spec:
  type: {{ .Values.ollama.service.type }}

  selector:
    app: ollama

  ports:
    - name: http
      port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      protocol: TCP